name: Docker build

on:
  pull_request:
    paths:
    - '.github/workflows/build.yml'
    - 'Dockerfile'
    - 'entrypoint.sh'
    branches: [ main ]

env:
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  REGION: "ap-southeast-3"
  PROJECT_ID: "c847fb717563484fa95d18a75ae7831c"
  CLUSTER_ID: "507c33b6-c387-11eb-b949-0255ac1001ea"

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yikunkero/spark-master-test-maven-arm:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  self-host-job:
    name: Run job on self-host
    needs: docker-build
    runs-on: self-hosted
    container:
      image: yikunkero/spark-master-test-maven-arm:latest
    steps:
      - name: Run Test Only
        run: |
          /entrypoint.sh

  cce-container-job:
    runs-on: ubuntu-20.04
    needs: docker-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get kubectl
        run: |
          curl -sL https://dl.k8s.io/v1.19.0/kubernetes-client-linux-amd64.tar.gz | tar zx -C $HOME/
          export PATH=PATH:$HOME/kubernetes/client/bin
      - uses: huaweicloud/cce-cluster-credentials@v1
        with:
          region: "${{ env.REGION }}"
          access-key-id: "${{ env.ACCESS_KEY_ID }}"
          access-key-secret: "${{ env.SECRET_ACCESS_KEY }}"
          project-id: "${{ env.PROJECT_ID }}"
          cluster-id: "${{ env.CLUSTER_ID }}"

      - name: Run with specific image
        run: |
          kubectl config use-context external
          kubectl run --rm -i --privileged=true --image yikunkero/spark-master-test-maven-arm:latest spark-master-test-maven-arm-`date '+%Y%m%d%H%M%y'` --restart=Never --requests "cpu=8"
          STATUS=$?
          echo "Status: $STATUS"
