name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yikunkero/spark-master-test-maven-arm:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  build:
    runs-on: self-hosted
    container:
      image: yikunkero/spark-master-test-maven-arm:latest
    steps:
      # Runs a single command using the runners shell
      # build/mvn -fn -Phadoop-2.7 -Pyarn -Phive -Phive-2.3 -Phive-thriftserver -Pkinesis-asl -Pmesos --fail-at-end test -pl :spark-core_2.12,:spark-unsafe_2.12
      - name: Run Test Only
        run: |
          whoami
          /entrypoint.sh
