# This is a basic workflow to help you get started with Actions
name: Test Only
# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    container:
      image: yikunkero/spark-master-test-maven-arm-1-notest:latest
