# This is a basic workflow to help you get started with Actions
name: CI on 32u(2)

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    container:
      image: yikunkero/spark-master-test-maven-arm-1-notest:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a multi-line script
        run: |
          set -ex
          cd /spark-master-test-maven-arm
          build/mvn -fn -Phadoop-2.7 -Pyarn -Phive -Phive-2.3 -Phive-thriftserver -Pkinesis-asl -Pmesos --fail-at-end test -pl :spark-graphx_2.12,:spark-core_2.12
