name: Run Spark Master Test Python on ARM

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 */3 * * *'

env:
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  REGION: "ap-southeast-3"
  PROJECT_ID: "c847fb717563484fa95d18a75ae7831c"
  CLUSTER_ID: "75712c59-f430-11eb-8809-0255ac1001df"

jobs:
  pyspark-arm:
    name: Test Spark on ARM64 - ${{ matrix.modules }}
    strategy:
      # ${{ matrix.job_type }}
      matrix:
        job_type:
          - python
          - build

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get kubectl
        run: |
          curl -sL https://dl.k8s.io/v1.19.0/kubernetes-client-linux-amd64.tar.gz | tar zx -C $HOME/
          export PATH=PATH:$HOME/kubernetes/client/bin

      - name: Get ARM cluster credetials
        uses: huaweicloud/cce-cluster-credentials@v1
        with:
          region: "${{ env.REGION }}"
          access-key-id: "${{ env.ACCESS_KEY_ID }}"
          access-key-secret: "${{ env.SECRET_ACCESS_KEY }}"
          project-id: "${{ env.PROJECT_ID }}"
          cluster-id: "${{ env.CLUSTER_ID }}"

      - name: Run build and test job
        run: |
          kubectl config use-context external
          kubectl run --rm -i --image yikunkero/spark-multiarch:latest --image-pull-policy=Always spark-multiarch-`date '+%Y%m%d%H%M%y'` --restart=Never --requests "cpu=2,memory=4Gi" ${{ matrix.job_type }}
          STATUS=$?
          echo "Status: $STATUS"
          if [[ $STATUS -ne 0 ]]; then echo "Falsing..."; /bin/false; fi
